-- Migration 016: Add destination detailed sections as JSONB columns
ALTER TABLE destinations 
  ADD COLUMN IF NOT EXISTS intro_copy JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS why JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS courses_list JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS requirements_detail JSONB DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS intakes_list JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS costs_list JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS scholarships_list JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS faq JSONB DEFAULT '[]'::jsonb;

-- Update details for United Kingdom (uk)
UPDATE destinations SET 
  intro_copy = '["The United Kingdom is a global education powerhouse, hosting some of the oldest and most prestigious universities in the world. For Nepali students, the UK offers an unparalleled blend of academic history, cutting-edge research, and modern industry connections.","One of the biggest advantages of studying in the UK is the speed of education. Bachelor''s degrees are typically completed in three years, and Master''s degrees take just one year, reducing your overall tuition fees and living costs.","Furthermore, the UK''s Graduate Route (PSW) offers a fantastic opportunity to kickstart your international career, allowing you to work or look for work for up to two years after graduation."]'::jsonb,
  why = '["Shorter degree routes (1-year Master''s, 3-year Bachelor''s)","High academic standards from world-renowned institutions","2-year Graduate Route post-study work visa","Large and welcoming Nepali student community"]'::jsonb,
  courses_list = '[{"title":"1. Business Administration & MBA","description":"UK business schools are globally accredited and feature strong connections with European financial hubs. Programs focus on global commerce, entrepreneurship, and leadership."},{"title":"2. Data Science & Artificial Intelligence","description":"With high demand for tech professionals, UK universities offer advanced degrees in machine learning, big data analysis, and software development, backed by state-of-the-art laboratory facilities."},{"title":"3. Engineering & Technology","description":"From civil and mechanical to aerospace engineering, UK degrees are internationally accredited and heavily oriented around practical industry placements."},{"title":"4. Healthcare & Public Health","description":"The UK''s NHS system aligns closely with university programs, offering nursing, public health, and administration students exceptional clinical exposure and post-study career pathways."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: Minimum 60% (GPA 2.4+) in high school (+2) board exams. Postgraduate: Minimum 55% or GPA 2.75+ in a relevant Bachelor''s degree.","english":"IELTS overall 6.0 (no band less than 5.5) for Bachelor''s; 6.5 (no band less than 6.0) for Master''s. Equivalent scores in PTE Academic (50-58) are widely accepted.","financial":"Evidence of first-year tuition fees plus living expenses (£10,224 outside London, £13,347 inside London) held in a recognized bank account for a minimum of 28 consecutive days.","genuine":"The UK government utilizes a Genuine Student assessment. You must show genuine intent, write a convincing Statement of Purpose (SOP), and pass university/credibility interviews to secure your CAS."}'::jsonb,
  intakes_list = '[{"title":"Autumn Intake","period":"September / October","deadline":"April to July","desc":"The primary academic intake offering the widest selection of courses, campuses, and scholarship options."},{"title":"Spring Intake","period":"January / February","deadline":"August to November","desc":"The second major intake, highly popular for business, computing, and management studies."},{"title":"Summer Intake","period":"May / June","deadline":"December to February","desc":"A smaller intake offered by select institutions, ideal for accelerated programs and pathway routes."}]'::jsonb,
  costs_list = '[{"category":"Undergraduate Tuition","range":"£12,000 – £20,000 / year","desc":"Varies by course type (classroom vs. laboratory-based) and university ranking."},{"category":"Postgraduate Tuition","range":"£13,000 – £25,000 / year","desc":"Master''s degrees are only 1 year in length, keeping the total tuition cost highly competitive."},{"category":"Living Expenses","range":"£9,200 – £12,000 / year","desc":"Covers accommodation, food, travel, and personal utilities. London is significantly higher."},{"category":"Immigration Health Surcharge (IHS)","range":"£776 / year","desc":"Mandatory fee that grants you full access to the UK''s National Health Service (NHS) for free medical care."}]'::jsonb,
  scholarships_list = '[{"name":"Chevening Scholarships","details":"The UK government''s global scholarship program, covering full tuition fees, monthly living allowances, return airfares, and visa fees for postgraduate courses."},{"name":"GREAT Scholarships","details":"Jointly funded by the UK government and participating universities, offering a minimum of £10,000 towards one-year postgraduate tuition."},{"name":"Commonwealth Scholarships","details":"Aimed at high-achieving students from developing commonwealth countries, covering tuition and living allowances for Master''s and PhD studies."},{"name":"University Merit Scholarships","details":"Direct fee waivers offered by individual universities during the offer stage, ranging from £1,500 to £5,000 based on your academic GPA."}]'::jsonb,
  faq = '[["Why should I choose the UK for my higher education?","The UK offers world-class qualifications that are globally recognized. Shorter degree durations (typically 1 year for Master''s and 3 years for Bachelor''s) mean you save on both tuition and living costs while starting your career sooner."],["Is IELTS mandatory for studying in the UK?","While IELTS is the most popular English test, many UK universities also accept PTE Academic, TOEFL iBT, or even offer IELTS waivers based on high English marks in your high school (+2) board exams. We will check the specific requirements for your profile."],["What is the Post-Study Work (PSW) visa in the UK?","The Graduate Route allows international graduates to live and work in the UK for up to 2 years (3 years for PhD graduates) after completing their degree, without requiring a company sponsorship upfront."],["How much bank balance is required to apply for a UK student visa?","You must show tuition fees for the first year plus living expenses of £13,347 (for study in London) or £10,224 (for study outside London). These funds must be held in a bank account in your name or your parents'' names for at least 28 consecutive days."]]'::jsonb
WHERE slug = 'uk';

-- Update details for United States (usa)
UPDATE destinations SET 
  intro_copy = '["The United States remains the top destination for global education, hosting the majority of the world''s highest-ranking universities. Known for technological innovation, academic flexibility, and multicultural campuses, the US offers a transformative study experience.","In the US, you are not locked into one field from day one. The system encourages students to explore different subjects, declare majors later, and customize their curriculum to match their career aspirations.","Nepali students especially benefit from the STEM (Science, Technology, Engineering, and Math) extension, which grants graduates up to three years of post-study work rights in the country''s booming job market."]'::jsonb,
  why = '["Flexible curriculum allowing you to switch majors or customize degrees","STEM designation offering up to 3 years of post-study work (OPT)","Unmatched research facilities and funding opportunities","High availability of merit-based university scholarships and assistantships"]'::jsonb,
  courses_list = '[{"title":"1. Computer Science & Cybersecurity","description":"The US is the home of tech giants. Degrees offer cutting-edge knowledge in AI, cloud computing, and cybersecurity, with direct access to Silicon Valley and tech hubs."},{"title":"2. Business Analytics & Finance","description":"STEM-accredited business degrees merge statistical analysis, data modeling, and management science to prepare you for high-paying corporate roles."},{"title":"3. Engineering & Aerospace","description":"With advanced labs and corporate partnerships, US engineering programs offer practical experience and research funding in aerospace, mechanics, and electronics."},{"title":"4. Healthcare & Biotechnology","description":"Degrees in biology, pharmaceutical sciences, and healthcare administration place you at the forefront of global medical research and public health management."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: GPA of 2.5+ (60% equivalent) in high school (+2). Graduate: CGPA of 2.75+ in a 4-year Bachelor''s degree (or 3-year degree with post-grad qualification).","english":"IELTS 6.0 to 6.5, TOEFL iBT 79+, or Duolingo English Test (DET) score of 105 to 115. Some institutions offer conditional admission if you take language classes first.","financial":"You must demonstrate enough liquid funds (bank balance, certificates, education loans) to cover the first year''s tuition and living costs as stated on your I-20 form.","genuine":"The US Embassy assesses your F-1 non-immigrant intent. You must show that you are a genuine student, have a clear study plan, and possess strong financial and family ties to return to Nepal."}'::jsonb,
  intakes_list = '[{"title":"Fall Intake","period":"August / September","deadline":"December to April","desc":"The largest and most important intake. Offers the most scholarships, assistantships, and course selections."},{"title":"Spring Intake","period":"January / February","deadline":"July to October","desc":"The second major intake. Ideal for students who need more time to prepare test scores and documentation."},{"title":"Summer Intake","period":"May / June","deadline":"January to March","desc":"Limited availability. Primarily used for English pathway programs, transfers, or specialized short courses."}]'::jsonb,
  costs_list = '[{"category":"Tuition Fees (Undergraduate)","range":"$15,000 – $35,000 / year","desc":"Public universities and state colleges generally offer more affordable tuition than private universities."},{"category":"Tuition Fees (Postgraduate)","range":"$18,000 – $40,000 / year","desc":"Highly variable depending on the university rank and professional nature of the program (e.g., MBA)."},{"category":"Living Expenses","range":"$10,000 – $18,000 / year","desc":"Covers on-campus housing or off-campus shared apartments, food, utilities, and transport."},{"category":"Student Health Cover","range":"$1,500 – $3,000 / year","desc":"Mandatory health insurance provided by the university or an approved third-party provider."}]'::jsonb,
  scholarships_list = '[{"name":"Fulbright Student Program","details":"Highly prestigious bi-national program covering full tuition, living expenses, textbooks, airfare, and health insurance for Master''s/PhD programs."},{"name":"University Merit Scholarships","details":"Direct tuition fee waivers granted by universities at the time of admission, based on your high school GPA, SAT score, or undergraduate CGPA."},{"name":"Graduate Assistantships (GA/TA/RA)","details":"Offered to Master''s and PhD students. Covers full or partial tuition fees in exchange for part-time teaching, research, or administrative duties, plus a monthly stipend."},{"name":"Humphrey Fellowship Program","details":"A year-long professional development program for mid-career professionals, covering full travel, tuition, and living costs."}]'::jsonb,
  faq = '[["Is SAT or GRE mandatory for US universities?","Many US universities are ''test-optional'' or ''test-blind'' for admissions. However, having a good SAT score can significantly improve your chances of getting high-value merit scholarships, while a GRE score can aid in securing graduate assistantships."],["What is the F-1 visa interview like?","The F-1 student visa interview is a face-to-face conversation at the US Embassy in Kathmandu. It lasts 2-3 minutes. You must demonstrate strong academic intent, solid financial backing, and clear ties back to Nepal. EduMark conducts rigorous mock interviews to build your confidence."],["Can I work in the US on a student visa?","Yes, F-1 visa holders can work on-campus for up to 20 hours per week during academic semesters and full-time (40 hours per week) during holidays and breaks."],["What is OPT and STEM OPT?","Optional Practical Training (OPT) allows you to work in your field of study for 12 months after graduation. If your degree is STEM-designated (Science, Technology, Engineering, or Math), you can apply for a 24-month extension, giving you 3 years of work rights in the US."]]'::jsonb
WHERE slug = 'usa';

-- Update details for Australia (australia)
UPDATE destinations SET 
  intro_copy = '["Australia is a premier global study destination, hosting top-tier institutions, vibrant multicultural cities, and pristine natural landscapes. The country stands out for its practical approach to learning, focusing heavily on industry readiness and real-world experience.","Nepali students find a highly welcoming environment in Australia, backed by strong community networks and university support services. The student protection laws ensure that your investment in education is safe and recognized.","With flexible post-study work rights and regional campus incentives (which offer lower living costs and visa benefits), Australia offers a clear pathway to achieving your academic and professional goals."]'::jsonb,
  why = '["Practical-oriented educational model with strong emphasis on internships","High demand and post-study opportunities for nursing and hospitality routes","Flexible three-intake calendar per academic year","Excellent student protection laws under the ESOS framework"]'::jsonb,
  courses_list = '[{"title":"1. Nursing & Midwifery","description":"Highly sought after and accredited by the Australian Nursing and Midwifery Accreditation Council. Programs integrate theoretical coursework with intensive clinical placements in public and private hospitals."},{"title":"2. Information Technology & Cybersecurity","description":"Aligned with Australia''s digital transformation. Degrees focus on artificial intelligence, software engineering, cloud architecture, and database networks."},{"title":"3. Business, Commerce & Finance","description":"Accredited by major accounting and management bodies. Offers specialization in international trade, entrepreneurship, auditing, and corporate finance."},{"title":"4. Hospitality & Commercial Cookery","description":"Combines academic management training with hands-on kitchen and hotel experience. Graduates are in high demand in Australia''s booming tourism and leisure sector."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: Minimum 60% (GPA 2.8+ out of 4.0) in high school (+2). Postgraduate: Minimum 55% or CGPA of 2.75+ in a Bachelor''s degree from a recognized institution.","english":"Undergraduate: IELTS overall 6.0 (no band less than 5.5) or PTE Academic 50+. Postgraduate: IELTS overall 6.5 (no band less than 6.0) or PTE Academic 58+.","financial":"You must demonstrate funds to cover 1 year of tuition fees, 1 year of living costs (A$29,710 for primary applicant), and A$2,000 for travel. Acceptable sponsors are parents and siblings.","genuine":"The Genuine Student (GS) / GST statement must clearly articulate your career goals, why you chose Australia, how the course aligns with your past studies, and your intention to return home."}'::jsonb,
  intakes_list = '[{"title":"Semester 1 Intake","period":"February / March","deadline":"September to November (Previous Year)","desc":"The primary and largest intake. Almost all universities and courses are open during this time."},{"title":"Semester 2 Intake","period":"July / August","deadline":"January to April (Same Year)","desc":"The mid-year intake. Highly popular, offering excellent course selections and scholarship entries."},{"title":"Trimester 3 Intake","period":"November / December","deadline":"May to July (Same Year)","desc":"Offered by select universities and colleges. Ideal for fast-track business and computing pathways."}]'::jsonb,
  costs_list = '[{"category":"Undergraduate Tuition","range":"A$20,000 – A$45,000 / year","desc":"Varies depending on whether you choose a regional university or a top-ranked metropolitan campus."},{"category":"Postgraduate Tuition","range":"A$22,000 – A$50,000 / year","desc":"Covers coursework Master''s degrees, research-based programs, and specialized postgraduate diplomas."},{"category":"Living Expenses","range":"A$20,000 – A$29,710 / year","desc":"The official government guideline is A$29,710 per year, covering accommodation, food, transport, and utilities."},{"category":"Overseas Student Health Cover","range":"A$500 – A$800 / year","desc":"Mandatory medical insurance for the entire duration of your student visa, covering basic healthcare and hospital visits."}]'::jsonb,
  scholarships_list = '[{"name":"Australia Awards Scholarships","details":"Prestigious scholarships funded by the Department of Foreign Affairs and Trade (DFAT) for postgraduate studies, covering full tuition, travel, and living stipends."},{"name":"Destination Australia Scholarship","details":"Government program offering up to A$15,000 per year to support international students studying at regional campuses in regional Australia."},{"name":"University International Student Awards","details":"Merit-based scholarships offered directly by universities, granting 15% to 30% tuition fee reductions based on academic GPA."},{"name":"Vice-Chancellor''s Academic Excellence","details":"Competitive awards offered by top universities, covering 50% to 100% of the tuition fees for high-achieving applicants."}]'::jsonb,
  faq = '[["What is the ESOS Act in Australia?","The Education Services for Overseas Students (ESOS) Act protects the rights of international students, ensuring tuition protection, quality learning, and accurate information from providers."],["Which English proficiency tests are accepted for Australia?","IELTS and PTE Academic are the most widely accepted tests for both Australian admissions and student visa processing. Pearson Test of English (PTE) is especially popular among Nepali applicants."],["What is the Genuine Student (GS) / GST requirement?","The Genuine Student (GS) assessment requires applicants to prove they are visiting Australia temporarily for high-quality education. It involves evaluating your previous study, visa history, financial capacity, and study objectives."],["Can I get a post-study work visa in Australia?","Yes. The Temporary Graduate Visa (Subclass 485) allows graduates of Bachelor''s (2 years) and Master''s (2-3 years) programs to live, study, and work in Australia post-graduation."]]'::jsonb
WHERE slug = 'australia';

-- Update details for Finland (finland)
UPDATE destinations SET 
  intro_copy = '["Finland is globally celebrated for its innovation, high standard of living, and an education system that prioritizes student well-being and practical skills. For Nepali students seeking European quality, Finland offers a premium academic environment.","The country''s Universities of Applied Sciences (UAS) are directly linked with the industry, ensuring that engineering, IT, business, and health science courses include practical placements, internships, and project work.","Finland offers generous scholarships for non-EU students, and once you graduate, the government grants a two-year job seeker permit, allowing you to settle into a professional career in the Nordic region."]'::jsonb,
  why = '["Voted the happiest country in the world for several consecutive years","World-class, innovation-oriented higher education system","Generous scholarship schemes for English-taught programs","Excellent post-study residence permit for job-seeking (2 years)"]'::jsonb,
  courses_list = '[{"title":"1. Information Technology & Artificial Intelligence","description":"Finland is the birthplace of global tech innovations. Programs offer advanced knowledge in software development, AI, game design, and cybersecurity."},{"title":"2. Business Administration & Sustainable Commerce","description":"Focused on global business, entrepreneurship, and eco-friendly business practices. Designed to fit the modern European business landscape."},{"title":"3. Environmental Engineering & Green Energy","description":"World-leading research in sustainability, clean water technology, and circular economy. Prepares students for careers in green energy systems."},{"title":"4. Nursing & Healthcare","description":"Highly sought-after programs that combine intensive simulation-based learning with clinical training in Finland''s highly advanced healthcare system."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: Completion of secondary school (+2) with good marks. Postgraduate: Bachelor''s degree (3 or 4 years) in a relevant field. Many UAS require entrance exams.","english":"IELTS overall 6.0 (no band less than 5.5) or PTE Academic 55+. Some Universities of Applied Sciences (UAS) may waive the English test if your school instruction was in English.","financial":"You must prove that you have at least €560 per month (€6,720 per year) held in your personal bank account. This is the official living cost guideline for the residence permit.","genuine":"The Finnish Immigration Service (Migri) requires a residence permit application. You must submit valid academic records, proof of tuition payment, health insurance, and pass a credibility interview."}'::jsonb,
  intakes_list = '[{"title":"Autumn Intake","period":"August / September","deadline":"January (Joint Application Window)","desc":"The primary academic intake. Most English-taught Bachelor''s and Master''s courses accept applications during the joint application period in January."},{"title":"Spring Intake","period":"January","deadline":"September (Previous Year)","desc":"The second intake. Limited to select applied science programs and specific technical courses."}]'::jsonb,
  costs_list = '[{"category":"Tuition Fees (Bachelor''s / UAS)","range":"€8,000 – €11,000 / year","desc":"Applied science universities offer practical learning with competitive tuition rates."},{"category":"Tuition Fees (Master''s / Research)","range":"€10,000 – €15,000 / year","desc":"Offered by comprehensive research universities, with robust academic programs."},{"category":"Living Expenses","range":"€6,720 – €9,000 / year","desc":"Minimum government requirement is €6,720 per year. Covers student housing, food, and transport."},{"category":"Student Health Insurance","range":"€200 – €400 / year","desc":"Mandatory health insurance from an approved provider (e.g., Swisscare or SIP) is required for the residence permit."}]'::jsonb,
  scholarships_list = '[{"name":"Finland Scholarships","details":"Covers 100% of the tuition fee for the first year of Master''s studies at participating universities, plus a €5,000 relocation grant."},{"name":"University Tuition Fee Waivers","details":"Performance-based scholarships offered in the second and third years, granting 50% to 100% fee waivers to students who complete 55 ECTS credits annually."},{"name":"Early Bird Discounts","details":"Offered by most Universities of Applied Sciences, granting €1,000 to €1,500 tuition discount if you accept the offer and pay the fee within 2-3 weeks."}]'::jsonb,
  faq = '[["Why should I choose Finland for my higher studies?","Finland offers a world-renowned, student-centric education system focusing on research, critical thinking, and practice. It provides a safe, peaceful, and clean environment, and is globally recognized as the happiest country in the world."],["Are scholarships available for non-EU international students?","Yes. Most Finnish universities and Universities of Applied Sciences (UAS) offer merit-based scholarships. These can range from 20% to 100% tuition fee waivers, and postgrad research routes often have fully funded positions."],["Can I work in Finland while studying?","International students on a residence permit can work up to 30 hours per week during the academic terms, and full-time during holidays and summer breaks."],["What is the post-study residence permit in Finland?","Graduates of Finnish higher education institutions can apply for a 2-year residence permit to look for work or start a business, facilitating a smooth transition into the Nordic job market."]]'::jsonb
WHERE slug = 'finland';

-- Update details for Lithuania (lithuania)
UPDATE destinations SET 
  intro_copy = '["Lithuania is a hidden gem in Northern Europe, offering a high-quality education system, rich cultural heritage, and one of the most affordable living standards in the European Union. It is an ideal destination for budget-first students seeking Schengen exposure.","From historic public institutions like Vilnius University (established in 1579) to highly creative private applied colleges like SMK, Lithuanian education is characterized by innovation, student care, and practical skills.","Nepali students in Lithuania enjoy the benefits of a student visa that grants free travel across the Schengen area, part-time work rights up to 40 hours a week, and a post-study window to transition into the European market."]'::jsonb,
  why = '["Extremely affordable tuition fees and cost of living compared to Western Europe","Full access to the Schengen zone for travel and networking","Wide selection of English-taught programs at historic and modern institutions","Growing tech and startup economy offering excellent local opportunities"]'::jsonb,
  courses_list = '[{"title":"1. Aviation & Logistics Management","description":"Specialized business degrees in airport management, aviation security, and transport logistics, offering certifications and practical training."},{"title":"2. Information Technology & Multimedia","description":"Lithuania is a thriving Baltic tech hub. Degrees focus on software engineering, game programming, animation, and database systems."},{"title":"3. International Business & Marketing","description":"Designed around European business frameworks, preparing students for roles in multinational marketing, public relations, and sales."},{"title":"4. Healthcare & General Nursing","description":"Highly affordable medical and nursing degrees with clinical training that is fully recognized across the European Union."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: Completion of secondary school (+2) with a minimum of 55%. Postgraduate: Bachelor''s degree (3 or 4 years) in a related discipline.","english":"IELTS overall 5.5 to 6.0, PTE Academic 45+, or a Certificate of Medium of Instruction (MOI) confirming your previous education was taught in English.","financial":"You must demonstrate access to a minimum of €150 to €200 per month (approx. €2,400 per year) in a bank account under your name or a sponsor''s name.","genuine":"The Lithuanian National D Visa requires verification of your academic documents, university registration, accommodation booking, and basic financial capacity."}'::jsonb,
  intakes_list = '[{"title":"Autumn Intake","period":"September","deadline":"May to July","desc":"The primary intake. Almost all universities and applied science programs are open for applications."},{"title":"Spring Intake","period":"February","deadline":"September to November","desc":"The secondary intake. Popular for business, management, and aviation management courses."}]'::jsonb,
  costs_list = '[{"category":"Undergraduate Tuition","range":"€1,300 – €4,500 / year","desc":"Private colleges like SMK offer very competitive fees starting around €2,800/year."},{"category":"Postgraduate Tuition","range":"€2,500 – €6,000 / year","desc":"Master''s degrees are highly affordable and take 1.5 to 2 years to complete."},{"category":"Living Expenses","range":"€4,500 – €7,000 / year","desc":"Covers accommodation in student dormitories, food, public transport, and personal expenses."},{"category":"Health Insurance","range":"€150 – €300 / year","desc":"Required for the visa and covers basic medical treatments and emergency hospital care."}]'::jsonb,
  scholarships_list = '[{"name":"Lithuanian State Scholarships","details":"The government offers monthly stipends of €490 and tuition fee coverage for high-achieving international Master''s applicants."},{"name":"Institution Tuition Discounts","details":"SMK and Vilnius University offer partial scholarships (10% to 50% discount on tuition) for outstanding international students based on past GPA."}]'::jsonb,
  faq = '[["Why choose Lithuania for studying abroad?","Lithuania offers high-quality European education at a fraction of the cost of other EU nations. It has historic universities, modern applied science colleges, and is extremely safe and affordable for international students."],["Is the medium of instruction English?","Yes. All programs listed for international students are taught entirely in English. The universities also offer Lithuanian language classes for students interested in local culture and integration."],["Can I travel to other European countries?","Lithuania is a member of the Schengen Zone. With your Lithuanian student visa or temporary residence permit (TRP), you can travel freely to 29 European countries without additional visas."],["What is the work permit situation during studies?","International students in Lithuania can work part-time up to 40 hours per week during their studies. After graduation, you can extend your stay to find a job or start a business."]]'::jsonb
WHERE slug = 'lithuania';

-- Update details for South Korea (south-korea)
UPDATE destinations SET 
  intro_copy = '["South Korea is a dynamic hub of technological innovation, economic growth, and global entertainment (K-Culture). It offers an exceptionally safe, modern, and high-tech study environment for international students.","The South Korean education system is world-renowned for its academic discipline and research, with flagship universities producing leaders in tech, engineering, and business fields.","For Nepali students, South Korea offers affordable first-step options, especially through Korean Language Programs that act as a smooth pathway into top-tier university degrees with significant scholarship opportunities."]'::jsonb,
  why = '["World leader in technology, electronics, and digital media","Opportunity to learn Korean language and culture","Highly affordable tuition fees compared to Western destinations","Robust campus facilities and student support systems"]'::jsonb,
  courses_list = '[{"title":"1. Korean Language Programs","description":"Intensive 1-year language tracks offered by university-affiliated institutes, designed to take you from beginner to TOPIK level 3/4."},{"title":"2. Computer Science & AI","description":"Backed by companies like Samsung and Hyundai. Focuses on software engineering, robotics, cloud systems, and smart tech."},{"title":"3. Business Management & Global Trade","description":"Taught in English and Korean, business programs focus on East Asian commerce models, global logistics, and corporate management."},{"title":"4. Media, Film & Communication","description":"At the heart of the Hallyu wave. Focuses on digital content creation, television production, public relations, and cultural studies."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: GPA of 2.5+ in high school (+2). Graduate: Bachelor''s degree with good GPA. Strong academic records in mathematics and science help for tech routes.","english":"For English-taught programs: IELTS 5.5 to 6.0+, or TOEFL 79+. For Korean-taught programs: TOPIK level 3 or 4 is mandatory.","financial":"A certificate of bank deposit showing $20,000 (D-2 visa) or $10,000 (D-4 language visa) held in the applicant''s or sponsor''s account for at least 1 month.","genuine":"The South Korean Embassy in Kathmandu assesses your visa application. You must present verified academic documents, certificate of admission (COA), and clear financial sponsor details."}'::jsonb,
  intakes_list = '[{"title":"Spring Semester","period":"March","deadline":"September to November (Previous Year)","desc":"The primary academic intake in South Korea. The semester runs from March to June."},{"title":"Autumn Semester","period":"September","deadline":"April to June (Same Year)","desc":"The second academic intake. The semester runs from September to December."},{"title":"Language Intakes","period":"March, June, September, December","deadline":"3 to 4 months before start","desc":"Korean language programs run on a 4-term quarterly basis, providing high flexibility."}]'::jsonb,
  costs_list = '[{"category":"Korean Language Course","range":"1,200,000 – 1,800,000 KRW / term","desc":"A term lasts 10 weeks. There are 4 terms in a full academic year of language study."},{"category":"Undergraduate Tuition","range":"3,000,000 – 6,000,000 KRW / semester","desc":"Two semesters per year. Humanities are cheaper, while engineering and medicine are higher."},{"category":"Living Expenses","range":"6,000,000 – 10,000,000 KRW / year","desc":"Covers university dorms (very affordable) or off-campus shared rooms, food, and utilities."},{"category":"Health Insurance","range":"50,000 – 70,000 KRW / month","desc":"International students are automatically registered in the National Health Insurance (NHIS)."}]'::jsonb,
  scholarships_list = '[{"name":"Global Korea Scholarship (GKS)","details":"Fully funded government program covering full tuition fees, flight tickets, monthly allowance of 900,000 KRW, settlement support, and insurance."},{"name":"TOPIK Scholarship for Admissions","details":"Universities offer direct tuition fee discounts (30% to 70%) for the first semester based on your entry TOPIK level (Level 3, 4, 5, or 6)."},{"name":"GPA-Based Academic Scholarships","details":"Offered in subsequent semesters by universities, providing tuition waivers (20% to 100%) to students who maintain a high GPA (above 3.0 out of 4.5)."}]'::jsonb,
  faq = '[["Do I need to know Korean to study in South Korea?","While there are English-taught degree programs (like Yonsei''s Underwood college), most programs require Korean language proficiency (TOPIK level 3 or 4). Many Nepali students choose a Korean Language Pathway, studying language for 1 year before starting their degree."],["What is the TOPIK exam?","The Test of Proficiency in Korean (TOPIK) is the standardized exam used to measure Korean language skills. Scoring high on TOPIK can earn you substantial tuition scholarships (up to 70-100% discount)."],["How much bank balance is needed for a South Korean student visa?","For a degree program (D-2 visa), you must show a bank deposit of $20,000 held for at least 1-3 months. For a language course (D-4 visa), the requirement is $10,000."],["Is part-time work allowed in South Korea?","Yes, international students with a certain TOPIK level and good GPA can work part-time up to 20-30 hours per week during semesters and unlimited hours during vacations."]]'::jsonb
WHERE slug = 'south-korea';

-- Update details for Japan (japan)
UPDATE destinations SET 
  intro_copy = '["Japan is a global powerhouse of technology, engineering, and manufacturing. Famous for its precision, safety, and rich culture, Japan offers a unique and highly structured educational route for international students.","Most Nepali students choose the Japanese Language School pathway. You study Japanese intensively for 1 to 2 years, secure a high level of proficiency (JLPT N2 or N1), and then transition smoothly into a vocational college (Senmon Gakko) or a Bachelor''s/Master''s degree.","Japan features an exceptionally high graduate employment rate. With a shrinking domestic population, the Japanese government and industries actively recruit international graduates for professional careers in engineering, IT, hospitality, and healthcare."]'::jsonb,
  why = '["World-class, technology-driven economy with a strong discipline culture","Highly organized Japanese language pathway to degree study","Very high post-graduate employment and career placement rates (over 90%)","Extremely safe cities with low crime rate and clean student living"]'::jsonb,
  courses_list = '[{"title":"1. Japanese Language Programs","description":"Offered by language academies for 1 to 2 years, building the linguistic foundation required to pass JLPT N2/N1 exams for higher studies."},{"title":"2. Robotics & Mechatronics","description":"Japan leads the world in automation. Degrees focus on hardware design, electronic sensors, micro-controllers, and artificial intelligence."},{"title":"3. Automotive Engineering","description":"Backed by companies like Toyota and Honda, these programs offer direct workshop training, vehicle assembly science, and engine technology."},{"title":"4. Hospitality & Hotel Management","description":"Focuses on Omotenashi (Japanese hospitality culture), hotel operations, and culinary arts, leading to placements in international resorts."}]'::jsonb,
  requirements_detail = '{"academic":"Completion of 12 years of formal education (high school/+2) with a minimum of 50%. A consistent study history with no long unexplained gaps.","english":"For English-taught programs: IELTS 6.0+ or TOEFL 79+. For Japanese-taught routes: Basic N5 certificate (or 150 hours of study) for language schools.","financial":"You must show a financial sponsor (usually parents) with an annual income of NPR 15 Lakh+ and a bank deposit of NPR 20 Lakh to 25 Lakh.","genuine":"The Japanese Immigration Service requires a rigorous check of your sponsor''s source of funds, tax clearance records, and your relationship certificates."}'::jsonb,
  intakes_list = '[{"title":"April Intake","period":"April","deadline":"September to November (Previous Year)","desc":"The primary and most popular intake. Aligns with the Japanese academic year. Offers the longest study duration (2 years of language study)."},{"title":"October Intake","period":"October","deadline":"March to May (Same Year)","desc":"The second major intake. Popular for international programs and offering 1.5 years of language study."},{"title":"January & July Intakes","period":"January / July","deadline":"4 to 5 months before start","desc":"Niche intakes offered by select language academies for accelerated learning routes."}]'::jsonb,
  costs_list = '[{"category":"Japanese Language School","range":"¥700,000 – ¥850,000 / year","desc":"Covers school tuition, textbooks, and laboratory fees. Paid as a one-year installment before departure."},{"category":"National University Tuition","range":"¥535,800 / year","desc":"Standard fee set by the government for all national universities, plus a one-time admission fee of ¥282,000."},{"category":"Living Expenses","range":"¥1,000,000 – ¥1,500,000 / year","desc":"Includes student shared house or dormitory, food, public transport, and utility bills. Cheap outside Tokyo."},{"category":"National Health Insurance","range":"¥20,000 / year","desc":"Mandatory insurance that covers 70% of all medical expenses, making healthcare extremely cheap for students."}]'::jsonb,
  scholarships_list = '[{"name":"MEXT Scholarships","details":"Fully funded by the Japanese Ministry of Education, Culture, Sports, Science, and Technology, covering full tuition, monthly stipend, and flights."},{"name":"JASSO Honors Scholarship","details":"Monthly stipend of ¥48,000 for 12 months, awarded to outstanding self-supporting international students recommended by their school."},{"name":"Local Government & Foundation Awards","details":"Offered by local prefectures and corporate foundations (e.g. rotary clubs), providing ¥30,000 to ¥100,000 per month for living expenses."}]'::jsonb,
  faq = '[["What is a COE and how do I get it?","A Certificate of Eligibility (COE) is a document issued by the Japanese Ministry of Justice confirming you meet the entry requirements. Once your chosen school or university secures the COE, you submit it to the embassy in Kathmandu to get the student visa."],["Is Japanese language study necessary before applying?","Yes. For language schools, you need at least N5 level proficiency or a certificate showing 150 hours of Japanese study. Learning basic Japanese increases your COE approval rate and makes settling in much easier."],["Can I work part-time in Japan?","Yes. International students with a valid student visa can work up to 28 hours per week (8 hours per day during vacations) after receiving the ''Permission to Engage in Activity Other Than That Permitted'' at the airport."],["Are there English-taught degrees in Japan?","Yes. Several top national universities offer global programs (like Tokyo''s PEAK or Nagoya''s G30 programs) which are taught entirely in English. However, learning Japanese is still necessary for local job placements."]]'::jsonb
WHERE slug = 'japan';

-- Update details for India (india)
UPDATE destinations SET 
  intro_copy = '["India is a highly practical and popular destination for Nepali students, offering quality professional education in medicine, engineering, nursing, and business management. It provides a familiar cultural environment, making it easy to adapt.","Major student hubs like Bangalore, Chennai, Pune, and Delhi NCR host hundreds of top colleges equipped with modern laboratories, library systems, and direct placement cells that coordinate with multinational corporations.","Studying in India does not require a student visa or passport for Nepali citizens, and the overall expenses (fees and hostel costs) are highly affordable, starting from as low as NPR 5 to 6 Lakh for complete degree programs."]'::jsonb,
  why = '["No visa or passport required for Nepali citizens to study and live","Highly affordable fee structures with close cultural and geographical proximity","Top-tier professional colleges with global rankings and AICTE/INC approvals","Strong placement cells providing direct access to multinational companies"]'::jsonb,
  courses_list = '[{"title":"1. Engineering & Technology (B.Tech)","description":"Offered in global hubs like Bangalore. Focuses on Computer Science, Information Science, Electronics, and AI with direct corporate placements."},{"title":"2. Medical, Paramedical & B.Sc Nursing","description":"Highly demanded courses regulated by the Indian Nursing Council (INC). Includes clinical training in multi-specialty hospitals."},{"title":"3. Pharmacy (B.Pharm / Pharm.D)","description":"Regulated by the Pharmacy Council of India (PCI). Covers pharmaceutical chemistry, pharmacology, and drug manufacturing standards."},{"title":"4. Business Administration & MBA","description":"Industry-aligned management training with specializations in retail, human resources, finance, and digital marketing."}]'::jsonb,
  requirements_detail = '{"academic":"Minimum of 50% to 60% in +2 (Science stream for medical/engineering, Commerce/Arts for business). Professional councils have specific subject marks (e.g. Biology for nursing).","english":"No formal English tests (like IELTS/PTE) are required. You must show that your medium of instruction in secondary school was English.","financial":"No bank balance or immigration proof is needed for the visa. You only need to pay the university application fees, secure an admission letter, and manage university payment schedules.","genuine":"No visa processing is required. You must secure an Equivalence Certificate from the Curriculum Development Centre (CDC) or TU in Nepal for your Indian degree registration."}'::jsonb,
  intakes_list = '[{"title":"Main Admission Intake","period":"August","deadline":"March onwards","desc":"The primary intake across all Indian colleges. Admissions start early in March. Note: A few colleges (2-3 colleges in India) also offer a minor January intake."}]'::jsonb,
  costs_list = '[{"category":"B.Tech Engineering Tuition","range":"₹1,20,000 – ₹2,50,000 / year","desc":"Varies by college rank. Computer Science engineering has the highest demand."},{"category":"B.Sc Nursing Tuition","range":"₹1,00,000 – ₹1,80,000 / year","desc":"Regulated by INC. Practical training charges may apply depending on the hospital network."},{"category":"B.Pharm / Pharmacy Tuition","range":"₹90,000 – ₹1,50,000 / year","desc":"Regulated by PCI. Covers classroom, labs, and manufacturing visits."},{"category":"Living / Hostel Expenses","range":"₹60,000 – ₹1,00,000 / year","desc":"Covers hostel accommodation and standard mess food (veg/non-veg)."}]'::jsonb,
  scholarships_list = '[{"name":"COMPEX Scholarship Scheme","details":"Administered by the Embassy of India, Kathmandu. Grants full or partial funding to Nepali students for engineering, nursing, agriculture, and dairy technology degrees."},{"name":"Study in India (SII) Scholarships","details":"Government program offering tuition fee waivers (G1: 100%, G2: 50%, G3: 25%) to qualified international students studying at partner colleges."},{"name":"EduMark Partner Scholarships","details":"Direct institutional fee waivers (10% to 50% discount on tuition) secured by EduMark through our direct tie-ups with leading Indian colleges."}]'::jsonb,
  faq = '[["Why should Nepali students choose India?","India offers high-quality professional education in fields like Medicine, Nursing, Engineering, and Pharmacy at a fraction of the cost of Western countries. There is no visa requirement, travel is cheap, and the culture is highly familiar."],["Is the Indian degree recognized in Nepal?","Yes. Indian degrees from recognized universities are fully equivalent and recognized in Nepal, provided the college has approvals from regulatory bodies like AICTE, INC, or PCI and gets registered with Nepali councils."],["What is the COMPEX Scholarship?","COMPEX is an undergraduate scholarship scheme run by the Indian Embassy in Kathmandu for Nepali students, offering full or partial funding for Engineering, Agriculture, Pharmacy, and Nursing courses in India."],["Do I need to take an entrance exam?","For medical courses (MBBS/BDS), you must clear the NEET exam in India or the CEE exam in Nepal. For engineering and management, many private universities have their own entrance exams or accept standard board marks."]]'::jsonb
WHERE slug = 'india';

-- Update details for Malta (malta)
UPDATE destinations SET 
  intro_copy = '["Malta is an increasingly popular study destination for Nepali students, offering an English-speaking environment in the heart of the Mediterranean. As a member of the European Union and the Schengen Zone, Malta provides direct pathways to broader European academic and professional networks.","For students prioritizing budget without compromising on quality, Maltese colleges and universities offer highly competitive tuition rates starting around €3,000 to €5,000 per year, with a cost of living significantly lower than in Western Europe.","English is one of the two official languages of Malta, which means all academic programs are taught in English and daily life is highly accessible for international students."]'::jsonb,
  why = '["Extremely affordable tuition fees and cost of living in the Mediterranean","English is an official language, making communication and integration easy","Study and travel freely across all 29 European Schengen countries","Strong hospitality and tourism sector with high student employment potential"]'::jsonb,
  courses_list = '[{"title":"1. Tourism & Hospitality Management","description":"Malta is a major European tourism hub. Degrees combine classroom learning with internship placements in top-tier hotels and resorts."},{"title":"2. Business Administration & MBA","description":"Focused on global trade, financial services, and entrepreneurship, aligning with Malta''s growing status as an offshore corporate center."},{"title":"3. Information Technology & Computing","description":"Programs in software development, cybersecurity, and game design, supported by Malta''s active tech startup ecosystem."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: GPA of 2.2+ (55% equivalent) in high school (+2). Graduate: Bachelor''s degree in a relevant field with at least 50% marks.","english":"IELTS 5.5 to 6.0, PTE 45+, or Medium of Instruction (MOI) letter if your school education was conducted entirely in English.","financial":"Proof of sufficient funds to cover tuition and a minimum of €150 to €200 per month for living expenses in a bank account under your name or a sponsor''s name.","genuine":"A Maltese student visa requires verification of academic documents, an official letter of acceptance from a licensed institution, and confirmed student accommodation."}'::jsonb,
  intakes_list = '[{"title":"Autumn Intake","period":"September / October","deadline":"May to July","desc":"The primary academic intake with the widest course availability."},{"title":"Spring Intake","period":"February / March","deadline":"October to December","desc":"The secondary intake, popular for business and management certificates."}]'::jsonb,
  costs_list = '[{"category":"Tuition Fees (Undergraduate)","range":"€3,000 – €6,000 / year","desc":"Highly affordable compared to Western European destinations."},{"category":"Tuition Fees (Postgraduate)","range":"€4,000 – €8,000 / year","desc":"Master''s degrees typically take 1 to 2 years to complete."},{"category":"Living Expenses","range":"€4,000 – €6,000 / year","desc":"Covers shared student housing, groceries, utilities, and public transport."}]'::jsonb,
  scholarships_list = '[{"name":"Endeavour Scholarship Scheme","details":"A national funding scheme supporting students pursuing postgraduate degrees in high-priority industrial sectors."},{"name":"Institutional Fee Waivers","details":"Merit-based fee reductions (10% to 30% discount) offered by private colleges for high academic performers."}]'::jsonb,
  faq = '[["Why study in Malta from Nepal?","Malta is a beautiful Mediterranean island and an official English-speaking nation in the European Union. It offers affordable tuition, a low cost of living, and is a gateway to the Schengen zone, allowing you to travel across Europe without a separate visa."],["What are the English language requirements for Malta?","While IELTS (5.5 - 6.0) or PTE Academic (45+) are widely accepted, some private colleges in Malta offer English interviews or accept Medium of Instruction (MOI) certificates from your previous school in Nepal."],["Can international students work in Malta?","Yes, international students in Malta are permitted to work part-time up to 20 hours per week after their first 90 days of arrival, helping cover their living expenses."]]'::jsonb
WHERE slug = 'malta';

-- Update details for Dubai (dubai)
UPDATE destinations SET 
  intro_copy = '["Dubai is a futuristic global hub that has emerged as a premier international education center, hosting branches of prestigious British, Australian, and American universities. For Nepali students, Dubai represents a safe, ultra-modern, and highly career-focused gateway.","The primary advantage of studying in Dubai is the ease of the visa process. Unlike Western destinations, Dubai has minimal document complexities and a near-perfect visa success rate, making it an excellent option for qualified applicants.","Additionally, students can study at branch campuses of world-renowned universities (such as Heriot-Watt University or Middlesex University) and receive the exact same degree certificate as the parent campus, with options for easy transfers."]'::jsonb,
  why = '["Zero tax on student earnings and highly competitive modern industries","Extremely high visa approval rate for Nepali students with minimal document complexity","Branch campuses of top UK, Australian, and US universities offering identical degrees","Global logistics, finance, and tourism hub with massive part-time job opportunities"]'::jsonb,
  courses_list = '[{"title":"1. Global Business & International Management","description":"Dubai is a crossroads of international trade. Programs focus on logistics, supply chain, finance, and global trade operations."},{"title":"2. Information Technology & Cyber Security","description":"Specialized training in artificial intelligence, cloud computing, and big data, aligned with Dubai''s Smart City initiatives."},{"title":"3. Tourism & Luxury Hospitality","description":"World-class hospitality programs with direct internship links to the world''s most luxurious hotel chains and event management groups."}]'::jsonb,
  requirements_detail = '{"academic":"Undergraduate: Minimum GPA of 2.2+ (55% equivalent) in high school (+2). Graduate: Relevant Bachelor''s degree with a minimum GPA of 2.5 or equivalent.","english":"IELTS 5.5 to 6.0, PTE 48+, or equivalent. Many branch universities allow institutional English entrance tests if you don''t have standard scores.","financial":"Proof of ability to cover tuition fees and basic living costs. Dubai does not require long-term bank holding deposits, making financial proof very simple.","genuine":"Admission relies on university sponsorship. Once accepted, the university processes your student visa with the Dubai General Directorate of Residency and Foreigners Affairs (GDRFA)."}'::jsonb,
  intakes_list = '[{"title":"Autumn Intake","period":"September","deadline":"June to August","desc":"The main intake offering all courses and scholarship slots."},{"title":"Spring Intake","period":"January","deadline":"October to December","desc":"The second major intake, popular for postgraduate business paths."},{"title":"Summer Intake","period":"May","deadline":"February to April","desc":"Ideal for foundational paths, language prep, and specific business programs."}]'::jsonb,
  costs_list = '[{"category":"Tuition Fees (Undergraduate)","range":"AED 40,000 – AED 75,000 / year","desc":"Covers branch campus tuition, matching UK/Australian degree qualifications."},{"category":"Tuition Fees (Postgraduate)","range":"AED 50,000 – AED 90,000 / year","desc":"Master''s degrees typically last 1 to 2 years, with flexible payment plans."},{"category":"Living / Hostel Expenses","range":"AED 25,000 – AED 45,000 / year","desc":"Includes shared student student accommodation, utilities, meals, and local transit."}]'::jsonb,
  scholarships_list = '[{"name":"Branch Campus Merit Scholarships","details":"Merit-based tuition discounts (15% to 30%) offered directly by branch universities based on academic marks."},{"name":"Corporate & Partner Sponsorships","details":"Partial fee waivers and paid internship packages co-funded by Dubai-based industry partners."}]'::jsonb,
  faq = '[["Why study in Dubai from Nepal?","Dubai hosts top-tier global university branch campuses (from the UK, Australia, etc.) where you can earn an identical degree at a lower tuition fee. The student visa process is highly straightforward with a near 100% approval rate, and no strict bank funds holding rules."],["Can I transfer to the home campus in the UK or Australia?","Yes, one of the biggest advantages of branch campuses in Dubai (such as Heriot-Watt or Wollongong) is the seamless credit transfer options to their main campuses in the UK or Australia after 1 or 2 years of study."],["What are the working rights for students in Dubai?","International students in Dubai can work part-time in designated free zones and retail/hospitality sectors, as well as secure corporate internships, with zero income tax."]]'::jsonb
WHERE slug = 'dubai';

